
var Bing={AppID:'736B9EDC859ED6916C020E0D75E4436ABC99D2EE',arrLanguagesForSpeak:null,arrRequestQueue:[],ERROR_JSONPARSE:"The server returned an incorrectly formatted response",ERROR_UNKNOWN:"An unknown error has occurred",CLASS_BING_BUTTONAUDIOPLAYER:"whywontchromeplaywavfileswithoutlockingupandwhyusewavanyway",Request:function(request){var xhr=new XMLHttpRequest();var url;if(request.template.options.sourceType=="TTS"){if(this.arrLanguagesForSpeak==null){url="http://api.microsofttranslator.com/V2/Ajax.svc/"+"GetLanguagesForSpeak"+"?"+"appId="+this.AppID;xhr.open('GET',url,true);xhr.Bing=this;xhr.onreadystatechange=function(){if(xhr.readyState==4){try{if(xhr.status!=200){var errorHTML=(xhr.status==0?Bing.ERROR_UNKNOWN:xhr.status+" "+xhr.statusText);var err=new Error();throw err;}
errorHTML=Bing.ERROR_JSONPARSE;this.Bing.arrLanguagesForSpeak=JSON.parse(xhr.responseText);if(this.Bing.arrLanguagesForSpeak==null){var err=new Error();throw err;}}catch(e){for(var q in Bing.arrRequestQueue){var req=this.Bing.arrRequestQueue[q];SendRequestWithTabIfPossible(req.tab,{msg:req.msgSet,index:req.index,templateId:req.template.id,data:{errorHTML:errorHTML}});}
this.Bing.arrRequestQueue=[];return;}
for(var q in this.Bing.arrRequestQueue)
this.Bing.Request(Bing.arrRequestQueue[q]);this.Bing.arrRequestQueue=[];}};this.arrRequestQueue.push(request);xhr.send(null);return;}
if(request.template.options.autoDetectLanguage==true){url="http://api.microsofttranslator.com/V2/Ajax.svc/"+"Detect"+"?"+"appId="+this.AppID+"&"+"text="+encodeURIComponent(request.text.substr(0,512));xhr.open('GET',url,true);xhr.req=request;xhr.Bing=this;xhr.onreadystatechange=function(){if(xhr.readyState==4){var detectedLanguage;try{if(xhr.status!=200){var errorHTML=(xhr.status==0?Bing.ERROR_UNKNOWN:xhr.status+" "+xhr.statusText);var err=new Error();throw err;}
errorHTML=Bing.ERROR_JSONPARSE;detectedLanguage=JSON.parse(xhr.responseText);if(detectedLanguage==null){var err=new Error();throw err;}}catch(e){SendRequestWithTabIfPossible(xhr.req.tab,{msg:xhr.req.msgSet,index:xhr.req.index,templateId:xhr.req.template.id,data:{errorHTML:errorHTML}});return;}
xhr.req.template.options.autoDetectLanguage=false;xhr.req.template.options.detectedLanguage=detectedLanguage;this.Bing.Request(xhr.req);}};xhr.send(null);return;}
function IsSpeakableLanguage(lang){var knownLanguageInfo=Bing.GetLanguageInfo(lang);if(knownLanguageInfo&&knownLanguageInfo.lang!=null)
lang=knownLanguageInfo.lang;for(var x in Bing.arrLanguagesForSpeak){if(Bing.arrLanguagesForSpeak[x]==lang)
return lang;}
return null;}
var bingForSpeakLanguage,language;var language;if(request.template.options.detectedLanguage&&(bingForSpeakLanguage=IsSpeakableLanguage(request.template.options.detectedLanguage))!=null)
language=bingForSpeakLanguage;else if((bingForSpeakLanguage=IsSpeakableLanguage(request.template.options.language))!=null)
language=bingForSpeakLanguage;else
language="en";url="http://api.microsofttranslator.com/V2/Ajax.svc/"+request.template.options.method+"?"+"appId="+this.AppID+"&"+"language="+language+"&"+"format=audio/wav&"+"text="+encodeURIComponent(request.text.substr(0,512));var languageInfo=Bing.GetLanguageInfo(language);xhr.spokenLanguage=language;xhr.spokenLanguageName=languageInfo.name;xhr.srcSpokenLanguageIcon=languageInfo.urlFlag;}
else if(request.template.options.sourceType=="method"){url="http://api.microsofttranslator.com/V2/Ajax.svc/"+request.template.options.method+"?"+"appId="+this.AppID+"&"+
(request.template.options.srcLang&&request.template.options.srcLang.length>0?("from="+request.template.options.srcLang+"&"):"")+"to="+request.template.options.destLang+"&"+"text="+encodeURIComponent(request.text.substr(0,512));}
else{url="http://api.bing.net/json.aspx?"+"AppId="+Bing.AppID+"&"+"sources="+request.template.options.sourceType+"&"+"query="+encodeURIComponent(request.text.substr(0,512));}
xhr.open('GET',url,true);xhr.Bing=this;xhr.onreadystatechange=function(){if(xhr.readyState==4){if(xhr.status!=200){var errorHTML=(xhr.status==0?Bing.ERROR_UNKNOWN:xhr.status+" "+xhr.statusText);SendRequestWithTabIfPossible(request.tab,{msg:request.msgSet,index:request.index,templateId:request.template.id,data:{errorHTML:errorHTML}});return;}
try{res=JSON.parse(xhr.responseText);if(res==null){var err=new Error();throw err;}}catch(e){SendRequestWithTabIfPossible(request.tab,{msg:request.msgSet,index:request.index,templateId:request.template.id,data:{errorHTML:Bing.ERROR_JSONPARSE}});return;}
var data=xhr.Bing.Parse(res,xhr,request.template);if(data){SendRequestWithTabIfPossible(request.tab,{msg:request.msgSet,index:request.index,templateId:request.template.id,data:data,});}}};xhr.send(null);},Parse:function(res,xhr,template){if(template.options.sourceType=="TTS"){return({url:res,spokenLanguage:xhr.spokenLanguage,spokenLanguageName:xhr.spokenLanguageName,srcSpokenLanguageIcon:xhr.srcSpokenLanguageIcon,});}
if(template.options.sourceType=="method"){if(template.options.method=="Translate"){var languageInfoDest=Bing.GetLanguageInfo(template.options.destLang);var languageInfoSrc=Bing.GetLanguageInfo(template.options.srcLang);var out={note:res,nameSrcLanguage:languageInfoSrc.name,urlSrcLanguageIcon:languageInfoSrc.urlFlag,};if(languageInfoDest){out.nameDestLanguage=languageInfoDest.name;out.urlDestLanguageIcon=languageInfoDest.urlFlag;out.googleLanguageCodes=languageInfoDest.altValues;}
return out;}}},arrLanguageNames:[{name:"English",value:"en",forSpeak:true,fileName:'england'},{name:"German",value:"de",forSpeak:true,fileName:'de'},{name:"Spanish",value:"es",forSpeak:true,fileName:'es'},{name:"French",value:"fr",forSpeak:true,fileName:'fr'},{name:"Italian",value:"it",forSpeak:true,fileName:'it'},{name:"Portuguese",value:"pt",forSpeak:true,fileName:'pt'},{name:"Russian",value:"ru",forSpeak:true,fileName:'ru'},{name:"Japanese",value:"ja",forSpeak:true,fileName:'jp'},{name:"Korean",value:"ko",forSpeak:true,fileName:'kr'},{name:"Chinese Simplified",value:"zh-chs",altValues:["zh-CN"],forSpeak:true,fileName:'cn'},{name:"Chinese Traditional",value:"zh-cht",altValues:["zh-TW"],forSpeak:true,fileName:'cn'},{name:"Chinese Simplified (ROC)",value:"zh-cn",altValues:["zh-CN"],forSpeak:true,fileName:'cn'},{name:"Chinese Traditional (HK)",value:"zh-hk",altValues:["zh-TW"],forSpeak:true,fileName:'cn'},{name:"Chinese Traditional (TW)",value:"zh-tw",altValues:["zh-TW"],forSpeak:true,fileName:'cn'},{name:"Catalan",value:"ca",forSpeak:true,fileName:'catalonia'},{name:"Polish",value:"pl",forSpeak:true,fileName:'pl'},{name:"Danish",value:"da",forSpeak:true,fileName:'dk'},{name:"Dutch",value:"nl",forSpeak:true,fileName:'nl'},{name:"Finnish",value:"fi",forSpeak:true,fileName:'fi'},{name:"Swedish",value:"sv",forSpeak:true,fileName:'se'},{name:"Arabic",value:"ar",filename:'arabic'},{name:"Bulgarian",value:"bg",fileName:'bg'},{name:"Czech",value:"cs",fileName:'cs'},{name:"Estonian",value:"et",fileName:'ee'},{name:"Greek",value:"el",fileName:'gr'},{name:"Hiatian Creole",value:"ht",fileName:'ht'},{name:"Hindi",value:"hi",fileName:'in'},{name:"Hebrew",value:"he",fileName:'il'},{name:"Hungarian",value:"hu",fileName:'hu'},{name:"Indonesian",value:"id",fileName:'id'},{name:"Latvian",value:"lv",fileName:'lv'},{name:"Lithuanian",value:"lt",fileName:'lt'},{name:"Norwegian",value:"no",fileName:'no'},{name:"Romanian",value:"ro",fileName:'ro'},{name:"Slovak",value:"sk",fileName:'sk'},{name:"Slovenian",value:"sl",fileName:'si'},{name:"Thai",value:"th",fileName:'th'},{name:"Turkish",value:"tr",fileName:'tr'},{name:"Ukrainian",value:"uk",fileName:'ua'},{name:"Vietnamese",value:"vi",fileName:'vn'},],GetLanguageInfo:function(value){var fileName='unknown';var name="Unknown";var forSpeak=false;var altValues=null;var lang=null;if(value&&value.length>0){for(var q in Bing.arrLanguageNames){if(Bing.arrLanguageNames[q].value==value||(Bing.arrLanguageNames[q].altValues&&Bing.arrLanguageNames[q].altValues.indexOf(value)!=-1)){if(Bing.arrLanguageNames[q].fileName)
fileName=Bing.arrLanguageNames[q].fileName;name=Bing.arrLanguageNames[q].name;forSpeak=Bing.arrLanguageNames[q].forSpeak;altValues=Bing.arrLanguageNames[q].altValues;lang=Bing.arrLanguageNames[q].value;break;}}}
return({urlFlag:chrome.extension.getURL('img/flags/'+fileName+'.png'),name:name,forSpeak:forSpeak,lang:lang,altValues:altValues,});},};