
var Flickr={AppID:'436508ad99838747018dc4bbafe5efe0',ERROR_UNKNOWN:"An unknown error has occurred",WARNING_NORESULTS:"We couldn't find anything matching your search <b><<TEXT>></b>",Request:function(request){var xhr=new XMLHttpRequest();var url="https://secure.flickr.com/services/rest/?"+"method=flickr.photos.search&"+"api_key="+Flickr.AppID+"&"+"content_type=7&"+"sort="+request.template.options.sort+"&"+"media="+request.template.options.media+"&"+"in_gallery="+(request.template.options.in_gallery==true?"true":"false")+"&"+"per_page="+request.template.options.per_page+"&"+"page="+(request.template.sessionData.page?request.template.sessionData.page:1)+"&"+"extras=date_uploaded,date_taken,owner_name,original_format,views,media,url_t,url_o&"+"text="+encodeURIComponent(request.text);xhr.open('GET',url,true);xhr.Flickr=this;xhr.onreadystatechange=function(){if(xhr.readyState==4){if(xhr.status!=200){var errorHTML=(xhr.status==0?Flickr.ERROR_UNKNOWN:xhr.status+" "+xhr.statusText);SendRequestWithTabIfPossible(request.tab,{msg:request.msgSet,index:request.index,templateId:request.template.id,data:{errorHTML:errorHTML}});return;}
var data=this.Flickr.Parse(xhr.responseXML,request);if(data){SendRequestWithTabIfPossible(request.tab,{msg:request.msgSet,index:request.index,templateId:request.template.id,data:data,});}}};xhr.send(null);},Parse:function(xmlDoc,request){if(xmlDoc.documentElement.attributes["stat"].value!="ok"){if(!xmlDoc.documentElement.firstChild.attributes)
return({errorHTML:Flickr.ERROR_UNKNOWN});else
return({errorHTML:xmlDoc.documentElement.firstChild.attributes["code"].value+" "+xmlDoc.documentElement.firstChild.attributes["msg"].value});}
var elems=xmlDoc.getElementsByTagName("photos");if(elems.length!=1)
return;var page=Number(elems[0].attributes["page"].value);var pages=Number(elems[0].attributes["pages"].value);var perpage=Number(elems[0].attributes["perpage"].value);var total=Number(elems[0].attributes["total"].value);if(total==0){var format=Flickr.WARNING_NORESULTS.replace("<<TEXT>>",request.text);return({warningHTML:format});}
else{var elems=xmlDoc.getElementsByTagName("photo");var html="";var arrObjPhotos=[];for(var i=0,photo;photo=elems[i];i++){var obj={thumbnail:{},};obj.thumbnail.width=parseInt(photo.getAttribute('width_t'));obj.thumbnail.height=parseInt(photo.getAttribute('height_t'));obj.thumbnail.src=photo.getAttribute('url_t');obj.title=photo.getAttribute('title');obj.datetaken=photo.getAttribute('datetaken')?new Date(photo.getAttribute('datetaken')):null;obj.ownername=photo.getAttribute('ownername');obj.originalformat=photo.getAttribute('originalformat');if(photo.getAttribute('url_o')){obj.originalimage={width:parseInt(photo.getAttribute('width_o')),height:parseInt(photo.getAttribute('height_o')),src:photo.getAttribute('url_o'),}}
obj.hrefPhoto='http://www.flickr.com/photos/'+photo.getAttribute('owner')+'/'+photo.getAttribute('id');obj.hrefProfile='http://www.flickr.com/photos/'+photo.getAttribute('owner')+'/';arrObjPhotos.push(obj);}
return({page:page,pages:pages,perpage:perpage,total:total,photos:arrObjPhotos,});}},};